name: New Glossary Term
description: "新的术语词"
title: "[新术语词]"
body:
  - type: input
    id: original
    attributes:
      label: "术语原文"
      description: "术语的原名"
      placeholder: "术语的原文，如entity"
    validations:
      required: true
  - type: input
    id: translation
    attributes:
      label: "术语的译文"
      description: "术语的译文"
    validations:
      required: true
  - type: dropdown
    id: state
    attributes:
      label: "state"
      description: "状态"
      options:
        - 推荐
        - 草稿
        - 弃置 
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "术语的描述"
    validations:
      required: true




